<a id='1'></a><center> <h3 style="background-color:orange; color:white" ><br>Telecommunication Industry Project<br></h3>

# Introduction
This Jupyter notebook is part of your learning experience in the study of applied statistics.

You will work with a data set that contains mobile phone prices and their specifications.

**Dataset Columns Information**

PID = a unique identifier for the phone model

Blue = whether the phone has bluetooth support or not

Wi_Fi = whether the phone has wifi support or not

Tch_Scr = whether the phone has touch screen support or not

Ext_Mem = whether the phone has external memory support or not

Px_h = number of pixels in the vertical axis of the phone

Px_w = number of pixels in the horizontal axis of the phone

Scr_h = height of the screen of the phone in centimetres (cm)

Scr_w = width of the screen of the phone in centimetres (cm)

Int_Mem = internal memory of the phone measured in megabytes (MB)

Bty_Pwr = maximum energy stored by the phone's battery measured in 
milli-Ampere-hours (mAh)

PC = resolution of the primary camera measued in megapixels (MP)

FC = resolution of the front camera measued in megapixels (MP)

RAM = random access memory available in the phone measured in gigabytes (GB)

Depth = depth of the mobile phone measured in centimetres (cm)

Weight = weight of the mobile phone measured in grams (g)

Price = selling price of the mobile phone in rupees

## Task 1 - Load and study the data

Import the libraries that will be used in this notebook

In [ ]:
# Load "numpy" and "pandas" for manipulating numbers and data frames
# Load "matplotlib.pyplot" and "seaborn" for data visualisation
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Load the csv file as pandas dataframe.

In [ ]:
# Read in the "Dataset" file as a Pandas Data Frame
df = pd.read_csv("Telecom Dataset.csv")
df.head()

NameError: name 'pd' is not defined

In [3]:
# Take a brief look at the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 17 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   PID      50 non-null     object
 1   Blue     50 non-null     object
 2   Wi_Fi    50 non-null     object
 3   Tch_Scr  50 non-null     object
 4   Ext_Mem  50 non-null     object
 5   Px_h     50 non-null     int64
 6   Px_w     50 non-null     int64
 7   Scr_h    50 non-null     int64
 8   Scr_w    50 non-null     int64
 9   PC       50 non-null     int64
 10  FC       50 non-null     int64
 11  Int_Mem  50 non-null     int64
 12  Bty_Pwr  50 non-null     int64
 13  RAM      50 non-null     int64
 14  Depth    50 non-null     int64
 15  Weight   50 non-null     int64
 16  Price    50 non-null     int64
dtypes: int64(12), object(5)
memory usage: 6.8+ KB

In [5]:
# Get the dimensions of the dataframe
df.ndim

2

In [6]:
# Get the row names of the dataframe
row_index = df.index
row_index

RangeIndex(start=0, stop=50, step=1)

In [7]:
# Get the column names of the dataframe
column = df.columns
column

Index(['PID', 'Blue', 'Wi_Fi', 'Tch_Scr', 'Ext_Mem', 'Px_h', 'Px_w', 'Scr_h',
       'Scr_w', 'PC', 'FC', 'Int_Mem', 'Bty_Pwr', 'RAM', 'Depth', 'Weight',
       'Price'],
      dtype='object')

In [8]:
# Look at basic information about the dataframe
df.describe()

,Px_h,Px_w,Scr_h,Scr_w,PC,FC,Int_Mem,Bty_Pwr,RAM,Depth,Weight,Price
count,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,2319.400000,1833.200000,6.500000,4.620000,42.160000,20.760000,173.760000,3740.000000,5.760000,3.440000,195.200000,33794.860000
std,598.400623,469.713069,2.042907,1.883223,30.174567,14.784934,261.771871,958.817299,2.759473,1.052887,75.761171,25037.535393
min,780.000000,460.000000,2.000000,1.000000,2.000000,2.000000,8.000000,2300.000000,2.000000,2.000000,80.000000,3297.000000
25%,2080.000000,1775.000000,5.000000,3.000000,12.000000,8.000000,32.000000,2800.000000,4.000000,3.000000,142.500000,19126.500000
50%,2580.000000,1980.000000,6.000000,5.000000,40.000000,16.000000,64.000000,3300.000000,5.000000,3.000000,190.000000,29349.500000
75%,2580.000000,2120.000000,8.000000,6.000000,64.000000,32.000000,128.000000,4500.000000,8.000000,4.000000,247.500000,43560.000000
max,2880.000000,2520.000000,10.000000,8.000000,128.000000,64.000000,1024.000000,5600.000000,12.000000,7.000000,400.000000,149000.000000

Observations:

There are 50 phones in the data set.

There are 17 features in the data set including the "PID" feature which is used as the row index labels.

There are no missing values in the data set.

<center>Let's try some logical operators to filter the data.<center>

![](https://th.bing.com/th/id/R.0592084daa6518e4fae97f47217ec69e?rik=vNqmiaTVSSo54w&riu=http%3a%2f%2f2.bp.blogspot.com%2f-ujABms6N-Cg%2fTyYwShdTjnI%2fAAAAAAAAAAs%2fktPbHdifidc%2fs1600%2fLogical%2bOperators.PNG&ehk=ww1gl1HB2PcZwPQNHWRUvcQ631Q3mzyHSxL9G4zUKT4%3d&risl=&pid=ImgRaw&r=0,width=700,height=400)

## Task 2 - Obtain the logical conditions for the features "Blue", "Wi_Fi", "Tch_Scr" and "Ext_Mem"

In [9]:
# Get the feature names of the dataframe

df['Blue']=='yes'

0      True
1      True
2     False
3     False
4     False
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12    False
13    False
14     True
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27     True
28     True
29    False
30     True
31    False
32     True
33    False
34     True
35    False
36     True
37     True
38     True
39     True
40     True
41     True
42     True
43    False
44     True
45    False
46     True
47     True
48     True
49     True
Name: Blue, dtype: bool

In [10]:
# Let's tackle these features: "Blue", "Wi_Fi", "Tch_Scr", "Ext_Mem"
con1 = (df['Blue'] == 'yes') & (df['Wi_Fi'] == 'yes') & (df['Tch_Scr'] == 'yes') & (df['Ext_Mem'] == 'yes')
con1

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9      True
10     True
11     True
12    False
13    False
14     True
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27     True
28     True
29    False
30     True
31    False
32     True
33    False
34     True
35    False
36     True
37     True
38     True
39     True
40     True
41     True
42     True
43    False
44     True
45    False
46     True
47    False
48    False
49    False
dtype: bool

In [11]:
# The children want phones that have the following: Bluetooth, WiFi, touch screen and external memory support
# Create a logical condition for this situation and store the logical values as "con1"
filtered = df[con1]

filtered

,PID,Blue,Wi_Fi,Tch_Scr,Ext_Mem,Px_h,Px_w,Scr_h,Scr_w,PC,FC,Int_Mem,Bty_Pwr,RAM,Depth,Weight,Price
8,DGS789M,yes,yes,yes,yes,2580,1920,6,3,32,16,8,2800,6,3,120,27688
9,ENG897N,yes,yes,yes,yes,2580,1980,5,3,64,32,64,4380,4,3,150,23456
10,EOP657N,yes,yes,yes,yes,2580,1920,6,3,32,16,128,2800,4,4,210,35460
11,ELS333L,yes,yes,yes,yes,2580,1920,8,6,64,32,8,4500,8,4,150,43980
14,NBN329S,yes,yes,yes,yes,2380,1820,5,3,16,8,8,2800,4,4,80,21972
27,SFK567Y,yes,yes,yes,yes,2580,2120,8,6,64,16,32,4300,8,3,200,49899
28,SSD000L,yes,yes,yes,yes,2580,2120,8,6,64,32,512,4200,8,3,270,36555
30,TVF078Y,yes,yes,yes,yes,2580,2120,8,6,64,32,512,4860,8,3,90,29999
32,TYS938L,yes,yes,yes,yes,2580,2120,8,6,64,32,1024,4860,8,3,120,46777
34,TYY453J,yes,yes,yes,yes,2880,2120,6,3,64,32,128,4400,8,4,150,61750
36,UST000T,yes,yes,yes,yes,2580,1980,10,8,64,32,32,3000,4,4,240,34589
37,USZ111S,yes,yes,yes,yes,2440,1980,5,3,48,32,128,4800,4,4,230,42300
38,VWV532Y,yes,yes,yes,yes,2580,1920,5,3,64,32,32,4860,8,4,310,39781
39,VYI666I,yes,yes,yes,yes,2440,1980,6,5,32,16,32,3200,4,4,180,33460
40,WER765T,yes,yes,yes,yes,2580,1980,5,3,64,32,128,3000,4,4,120,34780
41,WUV902Y,yes,yes,yes,yes,2580,1980,8,6,48,16,128,3400,4,3,140,28000
42,WZB298K,yes,yes,yes,yes,2580,1980,8,6,64,32,1024,5600,8,3,160,39000
44,XTL675G,yes,yes,yes,yes,2580,1980,10,8,64,32,512,4560,8,3,260,51230
46,YTR67TY,yes,yes,yes,yes,2580,1980,4,3,64,32,64,2800,4,3,200,56000

Observations:

The features "Blue", "Wi_Fi", "Tch_Scr" and "Ext_Mem" are binary in nature.

The children want all these features, so the logical condition "con1" has been obtained accordingly.

## Task 3 - Obtain the logical conditions for the features "Px_h" and "Px_w"

In [11]:
# Get the feature names of the dataframe

In [ ]:
# Let's tackle these features: "Px_h", "Px_w"

In [12]:
# Create a new feature called "Px" which stores the total resolution of the screen

In [13]:
# Create a histogram of the "Px" feature and also show the mean and the median

In [14]:
# The children want phones that have good screen resolutions
# Consider the phones that have screen resolutions greater than or equal to the median value in the data set
# Create a logical condition for this situation and store the logical values as "con2"

Observations:

The features "Px_h" and "Px_w" are respectively the number of pixels in the phone screen in the vertical and horizontal axes.

We created a new feature called "Px" which is the product of the features "Px_h" and "Px_w".

The median has been selected as a threshold in this case.

In case it is too strict, we can choose the mean as a threshold.

# Task 4 - Obtain the logical conditions for the features "Scr_h" and "Scr_w"

In [ ]:
# Let's tackle these features: "Scr_h", "Scr_w"

In [16]:
# Create a new feature called "Scr_d" which stores the length of the diagonal of the screen of the phone

In [17]:
# Create a histogram of the "Scr_d" feature and also show the quartiles

In [18]:
# The children want phones that have very good screen sizes
# Consider the phones that have screen sizes greater than or equal to the upper quartile value in the data set
# Create a logical condition for this situation and store the logical values as "con3"

Observations:

The features "Scr_h" and "Scr_w" are respectively the height and the width of the phone screen.

We created a new feature called "Scr_d" which is essentially the length of the screen diagonal.

The upper quartile has been selected as a threshold in this case as the children were very particular on this point.

In case it is too strict, we can choose the mean or the median as a threshold.

# Task 5 - Obtain the logical conditions for the features "PC" and "FC"

In [ ]:
# Let's tackle these features: "PC", "FC"

In [20]:
# Create a histogram of the "PC" feature and also show the mean and the median

In [21]:
# Create a histogram of the "FC" feature and also show the mean and the median

In [22]:
# The children want phones that have good primary and front camera resolutions
# Consider the phones that have primary and front camera resolutions greater than or equal to their respective mean values
# Create a logical condition for this situation and store the logical values as "con4"

Observations:

The features "PC" and "FC" are respectively the resolutions of the primary camera and the front camera.

The respective means have been selected as thresholds in this case.

In case it is too strict, we can choose the respective medians as thresholds.

# Task 6 - Obtain the logical conditions for the features "Int_Mem", "Bty_Pwr" and "RAM"

In [ ]:
# Let's tackle these features: "Int_Mem", "Bty_Pwr", "RAM"

In [23]:
# Create a histogram of the "Int_Mem" feature and also show the mean and the median

In [24]:
# Create a histogram of the "Bty_Pwr" feature and also show the mean and the median

In [25]:
# Create a histogram of the "RAM" feature and also show the mean and the median

In [26]:
# The children want phones that have good internal memory, battery power and RAM
# Consider the phones that have internal memory, battery power and RAM greater than or equal to their respective mean values
# Create a logical condition for this situation and store the logical values as "con5"

Observations

The features "Int_Mem", "Bty_Pwr" and "RAM" are respectively the internal memory, battery power and RAM of the phones.

The respective means have been selected as thresholds in this case.

.In case it is too strict, we can choose the respective medians as thresholds

# Task 7 - Obtain the logical conditions for the features "Depth" and "Weight"

In [27]:
# Let's tackle these features: "Depth", "Weight"

In [28]:
# Create a histogram of the "Depth" feature and also show the mean and the median

In [29]:
# Create a histogram of the "Weight" feature and also show the mean and the median

In [30]:
# The children want phones that are light weight and slim
# Consider the phones that have depth and weight less than or equal to the respective median values in the data set
# Create a logical condition for this situation and store the logical values as "con6"

Observations:

The features "Depth" and "Weight" are respectively the depth of the phone and the weight of the phone.

The respective medians have been selected as thresholds in this case.

In case it is too strict, we can choose the respective means as thresholds.

# Task 8 - Subset the data based on all the logical conditions

In [33]:
# Subset the dataframe using all the logical conditions that have been stored
# Store the subset of the dataframe as a new dataframe called "df1"

In [34]:
# Get the dimensions of the dataframe

In [35]:
# Sort the dataframe according to the "Price" feature in ascending order and display it

Observations:

Based on all the logical conditions obtained through analysis of the features, we are left with three phones.

The most expensive of these phones is the "TYS938L" model and the least expensive is the "TVF078Y" model.

We could let the children choose from these three phones as per their preferences.

# Task 9 - Study the variability of the features in the original data set

In [36]:
# Calculate the ratio of the standard deviation to the mean for all the numerical features in the dataframe
# Store these values in a new series wherein the rows are the features and the only column is the calculated ratio
# Name the series as "deviations"

In [37]:
# View the "deviations" series after sorting it in descending order

Observations:

The ratio of the standard deviation to the mean of a feature normalises it in a way.

This allows for comparison between multiple features.

The most variable feature in the original data set is the internal memory of the phones.

The least variable feature in the original data set is the number of screen pixels in the horizontal axis.

Although most features don't seem so variable, the prices of the phones are quite variable.

Feel free to investigate what could be the cause of this difference in variability.

Note: We encourage you to extend this analysis further and see what else you can find.

Note: Please refer to the official website of Python and its libraries for various Python documentations.

# Conclusion
1. We have used concepts of descriptive statistics to study and work with a data set that contains mobile phone specifications.

2. We were able to recommend three phone models to the client which she can then propose to her children.